--lua plugins configurations
require('plugins')
require('treesitter-conf')
--require('gitsigns')
--require('settings')
--require('nvim-compe')
--require('lsp-config')
--require('lsp-lua')
--require('lsp-python')
--require('lsp-js-ts')
--require('lsp-html')
--require('lsp-css')
--require('lsp-docker')
--require('lsp-java')
--require('lsp-vue')
--require('lsp-angular')
--require('lsp-yaml')
--require('lsp-config')
--require('lsp-efm')
--require('lspkind-config')
--require('dap')
--require('lsp-diagnostics') need to fix
--require('lsp-json')
--require('lightbulb-conf')

--vimscript plugins configurations
vim.cmd('source ~/.config/nvim/vimscript/general.vim')
vim.cmd('source ~/.config/nvim/vimscript/shortcuts.vim')
vim.cmd('source ~/.config/nvim/vimscript/airline.vim')
vim.cmd('source ~/.config/nvim/vimscript/startify.vim')
vim.cmd('source ~/.config/nvim/vimscript/vimwiki.vim')
vim.cmd('source ~/.config/nvim/vimscript/lsp-config.vim')
vim.cmd('source ~/.config/nvim/vimscript/parantheses-rainbow.vim')
vim.cmd('source ~/.config/nvim/vimscript/coc.vim')
vim.cmd('source ~/.config/nvim/vimscript/material-theme.vim')
vim.cmd('source ~/.config/nvim/vimscript/vimspector.vim')
